openapi:
  kakao: KakaoAK 1260ebdda741b8d4e807602bcdf000e7
spring:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true