openapi:
  kakao:
    api-config:
      key: KakaoAK 1260ebdda741b8d4e807602bcdf000e7
      url: https://dapi.kakao.com/v2/search/book
spring:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true